[[redirects]]
  from = "/auth/*"
  to = "http://34.139.180.11:8888/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "http://34.139.180.11:8888/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/carts/*"
  to = "http://34.139.180.11:8888/carts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/orders/*"
  to = "http://34.139.180.11:8888/orders/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/books/*"
  to = "http://34.139.180.11:8888/books/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/electronics/*"
  to = "http://34.139.180.11:8888/electronics/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fashion/*"
  to = "http://34.139.180.11:8888/fashion/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
