#!/bin/bash

# Start the web server
sudo service httpd start

# If using Apache on Ubuntu/Debian, use:
# sudo service apache2 start

# Enable the service to start on boot
sudo chkconfig httpd on

# If using Apache on Ubuntu/Debian, use:
# sudo update-rc.d apache2 defaults
